### ISSUE TITLE
aws-cni pod can get stuck in RUNNING state

### ISSUE THREAD

**Issue by sharadregoti** [aws/amazon-vpc-cni-k8s#2485]
**What happened**:
I have 2 nodegroups, one for running applications & other for running gitlab runner jobs.
In my Gitlab runner jobs nodegroup, I see this sudden error where aws-node pod is in `RUNNING` state but not ready to accept any requests.
When I describe the aws-node pod. I see this errors `Liveness probes failed: commad"
Check the below image for more info
![aws-node-describe](https://github.com/aws/amazon-vpc-cni-k8s/assets/24411676/2c653e0b-5aff-447c-8dc8-427e25703923)

POD NOT Reads
![aws-node-not-ready](https://github.com/aws/amazon-vpc-cni-k8s/assets/24411676/fb22c65f-5bfc-4ccf-a76e-ee9a492a8818)

The result of the above pod cascades to my new pods getting scheduled on this node & the pods that is getting terminated

![resultant-application-failure](https://github.com/aws/amazon-vpc-cni-k8s/assets/24411676/471660ef-f936-4303-bb70-697cc34e2165)

 

**Attach logs**
```
ttached a new ENI eni-0c0091f32b4ae6ba9 to instance"}"}]
[1] kubernetes.containers.var.log.aws-routed-eni.ipamd.log: [[1690979899.431117349, {}], {"log"=>"{"level":"debug","ts":"2023-08-02T12:38:19.431Z","caller":"ipamd/ipamd.go:2191","msg":"Current warm IP stats : target: 5, short: 1, over: 0, stats: Total IPs/Prefixes = 28/0, AssignedIPs/CooldownIPs: 24/0"}"}]
[2] kubernetes.containers.var.log.aws-routed-eni.ipamd.log: [[1690979899.431121369, {}], {"log"=>"{"level":"info","ts":"2023-08-02T12:38:19.431Z","caller":"ipamd/ipamd.go:924","msg":"Trying to allocate 1 IP addresses on ENI eni-0c0091f32b4ae6ba9"}"}]
[3] kubernetes.containers.var.log.aws-routed-eni.ipamd.log: [[1690979899.431123879, {}], {"log"=>"{"level":"debug","ts":"2023-08-02T12:38:19.431Z","caller":"ipamd/ipamd.go:924","msg":"PD enabled - false"}"}]
[0] kubernetes.containers.var.log.aws-routed-eni.ipamd.log: [[1690979899.822193903, {}], {"log"=>"{"level":"info","ts":"2023-08-02T12:38:19.822Z","caller":"ipamd/ipamd.go:924","msg":"Allocated 1 private IP addresses"}"}]
[1] kubernetes.containers.var.log.aws-routed-eni.ipamd.log: [[1690979899.823230819, {}], {"log"=>"{"level":"debug","ts":"2023-08-02T12:38:19.823Z","caller":"awsutils/awsutils.go:1568","msg":"Total number of interfaces found: 3 "}"}]
[2] kubernetes.containers.var.log.aws-routed-eni.ipamd.log: [[1690979899.823235679, {}], {"log"=>"{"level":"debug","ts":"2023-08-02T12:38:19.823Z","caller":"awsutils/awsutils.go:611","msg":"Found ENI MAC address: 0a:02:fd:73:9a:38"}"}]
[3] kubernetes.containers.var.log.aws-routed-eni.ipamd.log: [[1690979899.829469056, {}], {"log"=>"{"level":"debug","ts":"2023-08-02T12:38:19.829Z","caller":"awsutils/awsutils.go:611","msg":"Found ENI: eni-02915c495154328b6, MAC 0a:02:fd:73:9a:38, device 1"}"}]
[4] kubernetes.containers.var.log.aws-routed-eni.ipamd.log: [[1690979899.833145737, {}], {"log"=>"{"level":"debug","ts":"2023-08-02T12:38:19.833Z","caller":"awsutils/awsutils.go:611","msg":"Found ENI MAC address: 0a:94:7f:42:21:94"}"}]
[5] kubernetes.containers.var.log.aws-routed-eni.ipamd.log: [[1690979899.834143543, {}], {"log"=>"{"level":"warn","ts":"2023-08-02T12:38:19.834Z","caller":"awsutils/awsutils.go:626","msg":"failed to retrieve network/interfaces/macs/0a:94:7f:42:21:94/interface-id from instance metadata EC2MetadataError: failed to make EC2Metadata request\n<?xml version=\"1.0\" encoding=\"iso-8859-1\"?>\n<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\"\n\t\t \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n<html xmlns=\"http://www.w3.org/1999/xhtml\" xml:lang=\"en\" lang=\"en\">\n <head>\n  <title>404 - Not Found</title>\n </head>\n <body>\n  <h1>404 - Not Found</h1>\n </body>\n</html>\n\n\tstatus code: 404, request id: "}"}]
[6] kubernetes.containers.var.log.aws-routed-eni.ipamd.log: [[1690979899.834212924, {}], {"log"=>"{"level":"warn","ts":"2023-08-02T12:38:19.834Z","caller":"retry/retry.go:70","msg":"Failed to increase pool, error trying to discover attached ENIs on attempt 1/12: get attached ENIs: failed to retrieve ENI metadata for ENI: 0a:94:7f:42:21:94: EC2MetadataError: failed to make EC2Metadata request\n<?xml version=\"1.0\" encoding=\"iso-8859-1\"?>\n<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\"\n\t\t \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n<html xmlns=\"http://www.w3.org/1999/xhtml\" xml:lang=\"en\" lang=\"en\">\n <head>\n  <title>404 - Not Found</title>\n </head>\n <body>\n  <h1>404 - Not Found</h1>\n </body>\n</html>\n\n\tstatus code: 404, request id:  "}"}]
[7] kubernetes.containers.var.log.aws-routed-eni.ipamd.log: [[1690979899.938930147, {}], {"log"=>"{"level":"debug","ts":"2023-08-02T12:38:19.938Z","caller":"awsutils/awsutils.go:1568","msg":"Total number of interfaces found: 3 "}"}]
[8] kubernetes.containers.var.log.aws-routed-eni.ipamd.log: [[1690979899.938937017, {}], {"log"=>"{"level":"debug","ts":"2023-08-02T12:38:19.938Z","caller":"awsutils/awsutils.go:611","msg":"Found ENI MAC address: 0a:02:fd:73:9a:38"}"}]
[9] kubernetes.containers.var.log.aws-routed-eni.ipamd.log: [[1690979899.941879414, {}], {"log"=>"{"level":"debug","ts":"2023-08-02T12:38:19.941Z","caller":"awsutils/awsutils.go:611","msg":"Found ENI: eni-02915c495154328b6, MAC 0a:02:fd:73:9a:38, device 1"}"}]
[10] kubernetes.containers.var.log.aws-routed-eni.ipamd.log: [[1690979899.945364525, {}], {"log"=>"{"level":"debug","ts":"2023-08-02T12:38:19.945Z","caller":"awsutils/awsutils.go:611","msg":"Found ENI MAC address: 0a:94:7f:42:21:94"}"}]
[11] kubernetes.containers.var.log.aws-routed-eni.ipamd.log: [[1690979899.948488333, {}], {"log"=>"{"level":"debug","ts":"2023-08-02T12:38:19.948Z","caller":"awsutils/awsutils.go:611","msg":"Found ENI: eni-0c0091f32b4ae6ba9, MAC 0a:94:7f:42:21:94, device 2"}"}]
[12] kubernetes.containers.var.log.aws-routed-eni.ipamd.log: [[1690979899.955732726, {}], {"log"=>"{"level":"debug","ts":"2023-08-02T12:38:19.955Z","caller":"awsutils/awsutils.go:611","msg":"Found ENI MAC address: 0a:b5:84:db:14:84"}"}]
[13] kubernetes.containers.var.log.aws-routed-eni.ipamd.log: [[1690979899.958756773, {}], {"log"=>"{"level":"debug","ts":"2023-08-02T12:38:19.958Z","caller":"awsutils/awsutils.go:611","msg":"Found ENI: eni-0258f9222a5e82055, MAC 0a:b5:84:db:14:84, device 0"}"}]
[14] kubernetes.containers.var.log.aws-routed-eni.ipamd.log: [[1690979899.961249528, {}], {"log"=>"{"level":"debug","ts":"2023-08-02T12:38:19.961Z","caller":"retry/retry.go:70","msg":"ENI ID: eni-0c0091f32b4ae6ba9 IP Addr: [{\n  Primary: true,\n  PrivateIpAddress: \"10.53.73.209\"\n}], IPv4Prefixes:- [], IPv6Prefixes:- []"}"}]
[15] kubernetes.containers.var.log.aws-routed-eni.ipamd.log: [[1690979899.961254508, {}], {"log"=>"{"level":"debug","ts":"2023-08-02T12:38:19.961Z","caller":"retry/retry.go:70","msg":"No secondary IPv4 addresses/prefixes available yet on ENI eni-0c0091f32b4ae6ba9"}"}]
[16] kubernetes.containers.var.log.aws-routed-eni.ipamd.log: [[1690979900.181047367, {}], {"log"=>"{"level":"debug","ts":"2023-08-02T12:38:20.180Z","caller":"awsutils/awsutils.go:1568","msg":"Total number of interfaces found: 3 "}"}]
[17] kubernetes.containers.var.log.aws-routed-eni.ipamd.log: [[1690979900.181054057, {}], {"log"=>"{"level":"debug","ts":"2023-08-02T12:38:20.181Z","caller":"awsutils/awsutils.go:611","msg":"Found ENI MAC address: 0a:02:fd:73:9a:38"}"}]
[18] kubernetes.containers.var.log.aws-routed-eni.ipamd.log: [[1690979900.183525892, {}], {"log"=>"{"level":"debug","ts":"2023-08-02T12:38:20.183Z","caller":"awsutils/awsutils.go:611","msg":"Found ENI: eni-02915c495154328b6, MAC 0a:02:fd:73:9a:38, device 1"}"}]
[19] kubernetes.containers.var.log.aws-routed-eni.ipamd.log: [[1690979900.186052247, {}], {"log"=>"{"level":"debug","ts":"2023-08-02T12:38:20.185Z","caller":"awsutils/awsutils.go:611","msg":"Found ENI MAC address: 0a:94:7f:42:21:94"}"}]
[20] kubernetes.containers.var.log.aws-routed-eni.ipamd.log: [[1690979900.188391690, {}], {"log"=>"{"level":"debug","ts":"2023-08-02T12:38:20.188Z","caller":"awsutils/awsutils.go:611","msg":"Found ENI: eni-0c0091f32b4ae6ba9, MAC 0a:94:7f:42:21:94, device 2"}"}]
[21] kubernetes.containers.var.log.aws-routed-eni.ipamd.log: [[1690979900.190991376, {}], {"log"=>"{"level":"debug","ts":"2023-08-02T12:38:20.190Z","caller":"awsutils/awsutils.go:611","msg":"Found ENI MAC address: 0a:b5:84:db:14:84"}"}]
[22] kubernetes.containers.var.log.aws-routed-eni.ipamd.log: [[1690979900.194042743, {}], {"log"=>"{"level":"debug","ts":"2023-08-02T12:38:20.193Z","caller":"awsutils/awsutils.go:611","msg":"Found ENI: eni-0258f9222a5e82055, MAC 0a:b5:84:db:14:84, device 0"}"}]
[23] kubernetes.containers.var.log.aws-routed-eni.ipamd.log: [[1690979900.197672155, {}], {"log"=>"{"level":"debug","ts":"2023-08-02T12:38:20.197Z","caller":"retry/retry.go:70","msg":"ENI ID: eni-0c0091f32b4ae6ba9 IP Addr: [{\n  Primary: true,\n  PrivateIpAddress: \"10.53.73.209\"\n}], IPv4Prefixes:- [], IPv6Prefixes:- []"}"}]
[24] kubernetes.containers.var.log.aws-routed-eni.ipamd.log: [[1690979900.197677715, {}], {"log"=>"{"level":"debug","ts":"2023-08-02T12:38:20.197Z","caller":"retry/retry.go:70","msg":"No secondary IPv4 addresses/prefixes available yet on ENI eni-0c0091f32b4ae6ba9"}"}]
```

**What you expected to happen**:
This error should not have occured.

**How to reproduce it (as minimally and precisely as possible)**:
My hypothesis this error happen when a CPU gitlab job runs on that node or when aws-node does not get enough CPU
I think this is a similar issue #2389 

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.4", GitCommit:"fa3d7990104d7c1f16943a67f11b154b71f6a132", GitTreeState:"clean", BuildDate:"2023-07-20T02:11:13Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"25+", GitVersion:"v1.25.11-eks-a5565ad", GitCommit:"df109513ba589adaee235b4e658476275d1fde31", GitTreeState:"clean", BuildDate:"2023-06-16T17:35:00Z", GoVersion:"go1.19.10", Compiler:"gc", Platform:"linux/amd64"}
- CNI Version: v1.13.2-eksbuild.1
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):

**Comment by jdn5126** [comment]
@sharadregoti are you specifying CPU and memory limits for `aws-node` pods, and are those nodes heavily loaded? The liveness probe failures imply that the `aws-node` pod could not get the CPU for over 5 seconds, as you said.

Also, looking at the IPAMD logs you posted, the `aws-node` pods are failing to make EC2 API calls. Can you look into this? Maybe some security group is misconfigured or you changed IAM permissions or something

**Comment by sharadregoti** [comment]
There is only `cpu` request assigned of value 25m (No limits assigned) . The loading on node depends on the gitlab jobs being currently run, there are some jobs which take all the available CPU of node. 

Also I would like to mention this error started occurring after we upgraded EKS from 1.22 to 1.25 & also removed the default ENI & added these variables.
        - name: MINIMUM_IP_TARGET
          value: "15"
        - name: WARM_IP_TARGET
          value: "5"
          
As I said the aws cni works fine most of the time, It just goes unresponsive for 15-20 minutes & comes back to normal. This may be due to CPU issue, but doesn't fix of #2389 in 1.3.0 should fix this issue? (I'll try downgrading 1.3.0 & see)

Regarding IPAMD logs, as i said above vpc-cni works totally fine it just get unresponsive for some time.

**Comment by jdn5126** [comment]
#2389 does not fix any CPU issue, and I doubt the upgrade or WARM target values had an effect here. As a side note, I recommend upgrading to the latest version, v1.13.4, as v1.13.2 had an issue that lead to increased memory usage and was fixed in v1.13.3.

For your problem at hand, this sounds like a more general issue if the `aws-node` pod is being starved from the CPU for greater than 5 seconds. A lot will go wrong when nodes are under significant memory and CPU pressure, so you should be specifying limits for these GitLab jobs, otherwise they can starve other pods. There's nothing that the VPC CNI can do if another process is hogging all of the CPU
