### ISSUE TITLE
Race condition between aws-vpc-cni-k8s and systemd-networkd on AL2023

### ISSUE THREAD

**Issue by dracut5** [aws/amazon-vpc-cni-k8s#3162]
**What happened**:
Hi! 
We have faced weird behavior when some cronjobs in the EKS cluster fail occasionally due network timeouts. It occurs randomly and we were not even able to reproduce the issue for a long time, but when we got into that we found out that a node secondary network interface, which was created and attached by the Amazon VPC CNI plugin, didn't have an IP address assigned. And when a pod gets the ip address from the pool located on this secondary ENI it is unable to perform any network actions, the network is fully inaccessible.

It was the root cause of our problem, but we decided to proceed our investigation and figure out why the ip is absent, moreover, not every time.

**Attach logs**
At the initial phase the vpc-cni creates and attaches a secondary ENI to an instance to satisfy the condition MINIMUM_IP_TARGET=10. The plugin also configures the corresponded network interface by adding the primary IP address

```
{"level":"info","ts":"2024-12-27T13:22:35.562Z","caller":"networkutils/network.go:1019","msg":"Setting up network for an ENI with IP address 172.26.103.105, MAC address 06:78:44:01:96:d1, CIDR 172.26.100.0/22 and route table 2"}
{"level":"debug","ts":"2024-12-27T13:22:35.562Z","caller":"networkutils/network.go:1019","msg":"Setting up ENI's primary IP 172.26.103.105"}
{"level":"debug","ts":"2024-12-27T13:22:35.564Z","caller":"networkutils/network.go:1019","msg":"Adding IP address 172.26.103.105/22"}
```
At the same time, until _/etc/systemd/network/80-ec2.network.d/10-eks_primary_eni_only.conf_ appears, the systemd-networkd service takes the mentioned interface under control and runs dhcp client to get a lease
```
Dec 27 13:22:35 ip-172-26-101-7.eu-west-1.compute.internal systemd-networkd[1438]: ens6: Configuring with /usr/lib/systemd/network/80-ec2.network.
Dec 27 13:22:35 ip-172-26-101-7.eu-west-1.compute.internal systemd-networkd[1438]: ens6: Link UP
Dec 27 13:22:35 ip-172-26-101-7.eu-west-1.compute.internal systemd-networkd[1438]: ens6: Gained carrier
Dec 27 13:22:35 ip-172-26-101-7.eu-west-1.compute.internal systemd-networkd[1438]: ens6: Gained IPv6LL
Dec 27 13:22:39 ip-172-26-101-7.eu-west-1.compute.internal systemd-networkd[1438]: ens6: DHCPv4 address 172.26.103.105/22, gateway 172.26.100.1 acquired from 172.26.100.1
```
When _10-eks_primary_eni_only.conf_ file, which specifies what certain interfaces systemd-networkd should manage (only one to be more precisely - the primary ENI interface), is created the service decides to stop managing the device
```
Dec 27 13:22:43 ip-172-26-101-7.eu-west-1.compute.internal systemd-networkd[1438]: ens6: Unmanaging interface.
Dec 27 13:22:43 ip-172-26-101-7.eu-west-1.compute.internal systemd-networkd[1438]: ens6: DHCP lease lost
Dec 27 13:22:43 ip-172-26-101-7.eu-west-1.compute.internal systemd-networkd[1438]: ens6: DHCPv6 lease lost
```
This action results in the deletion of the assigned IP address since the lease should be released.

In the future our secondary interface, ens6, will be managed by aws-cni exclusively, but it knows nothing about IP address removal done by systemd-networkd. At the end we get the unrouted broken network interface and, as has been said before, when a pod obtains an IP address from the related pool it is just unable to reach any network endpoints. Plugin restart helps, but it is not a long term solution.

So, very likely, it is a race condition between the Amazon VPC CNI plugin and the systemd-networkd service - they are managing the same network interface at the same time due some circumstances.

It is worth mentioning that from time to time the secondary interface is able to keep assigned primary IP when the dhcp client hadn’t got a lease before "Unmanaging interface" event occurred.

**What you expected to happen**:

Secondary interfaces are managed only by Amazon VPC CNI plugin and get proper permanent network configuration during a node init process. 

**How to reproduce it (as minimally and precisely as possible)**:
1. Set MINIMUM_IP_TARGET slightly higher than the particular instance type ENI can handle, it will force the plugin to create and attach additional one while a node is starting. As example, for c7*.large types it will be 10 and more: ENI supports 10 ips max - 1 primary and 9 secondaries. 
2. Just create new instances from that template until you catch the issue - the secondary interface without any IP address.

**Anything else we need to know?**:
We found some workaround: decreasing MINIMUM_IP_TARGET to 9 in order to place all ips on one primary interface during the instance init process, it works for all instance types used in our environments. The vpc-cni can create other ones if needed, attach and configure them, but it prevents the race condition against systemd-networkd at the very start, before _10-eks_primary_eni_only.conf_ file exists. 

Merry Christmas and Happy New Year y'all :christmas_tree: 

**Environment**:
- Kubernetes version (use `kubectl version`): `v1.31.3-eks`
- CNI Version: `v1.19.0-eksbuild.1`, installed as EKS Add-on
- OS (e.g: `cat /etc/os-release`): `Amazon Linux 2023.6.20241212`
- Kernel (e.g. `uname -a`): `6.1.119-129.201.amzn2023.aarch64`
- Systemd: `252.23-2` 
- Previous CNI config, which caused the issue  
```
{
  "env": {
    "WARM_IP_TARGET": "2",
    "MINIMUM_IP_TARGET": "10",
    "MAX_ENI": "3"
  }
}
```

**Comment by orsenthil** [comment]
> So, very likely, it is a race condition between the Amazon VPC CNI plugin and the systemd-networkd service - they are managing the same network interface at the same time due some circumstances.

> Amazon Linux 2023.6.20241212


Thank you providing these details.

We had discovered this issue with the AMI and root caused it to same conclusions that you have come to.  Due to race between "amazon-ec2-net-utils" package installed AL2023 AMI (back then) and VPC CNI, the default gateway route for these secondary ENIs installed by CNI was deleted by amazon-ec2-net-utils. It was realized that the ENI and its routes were first initialized by the VPC CNI plugin, then, amazon-ec2-net-utils init came into action, subsequently removed those routes in the race.

A fix was made in this in https://github.com/awslabs/amazon-eks-ami/pull/1738 by `@M00nF1sh` 
And AMI with the fix was released - https://github.com/awslabs/amazon-eks-ami/releases/tag/v20240329


To avoid this issue, you will have to upgrade the worker node AMI to at-least `v20240329` or to the latest.

**Comment by dracut5** [comment]
Hi all once again! 
 
 Could someone take a look on this, please? We was able to find how to bypass the issue, but we are still not fully certain that it will work each time. 
 
 That fix in the EKS AMI project seems not a solution of this particular problem since the `10-eks_primary_eni_only.conf` file is eventually created and it includes the MAC address of primary ENI. If you need additional info I will try to provide any, which I have found. 
 Really appreciate any help and thank you in advance!
 
 P.S. Maybe I should submit a ticket for the AWS support team?

**Comment by orsenthil** [comment]
@dracut5, I will take a look at this and try to reproduce this with the information you have to provided.

**Comment by dracut5** [comment]
Sorry, forgot to add: we are using self-managed node groups in this case, not EKS managed.

**Comment by dracut5** [comment]
Hi @orsenthil,

Did you have a chance to try to reproduce the issue? Was it successful?
Could I provide some details, which make the research simpler?

Thanks a lot!

**Comment by orsenthil** [comment]
Hello @dracut5 , I haven't been able to reproduce this issue yet. 
I created an EKS with self-managed node group, although, MNG vs self-managed Node Group shouldn't matter for this.

```
[senthilx@88665a371033:~/github-issues/3162]$ cat cluster.yaml
# cluster.yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: test-race-condition
  region: us-west-2  # specify your desired region
[senthilx@88665a371033:~/github-issues/3162]$ cat nodegroup.yaml
# nodegroup.yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: test-race-condition
  region: us-west-2

nodeGroups:
  - name: self-managed-ng
    instanceType: t3.large
    desiredCapacity: 2
    minSize: 1
    maxSize: 4
    amiFamily: AmazonLinux2023
    labels:
      nodegroup-type: self-managed
    tags:
      nodegroup-role: worker
    ssh:
      allow: true
```

2. Since it t3.large instance, it has 3 ENIs and each CNI can support max of 12. But keeping reserved, it can support 11 ips per ENI. So, I set the `MINIMUM_IP_TARGET` to 14.

3. I scaled up nodes in my cluster. (The nodes came up with AMI ami-079182793d10affb9) 

```
eksctl scale nodegroup --cluster=$CLUSTER_NAME --name=self-managed-ng --nodes=4 --nodes-max=10 --nodes-min=0
```

And noticed the additional ENI allocated.

```
{"level":"debug","ts":"2025-01-11T02:05:07.084Z","caller":"datastore/data_store.go:1002","msg":"ENI eni-00bca9c5a3fda2c89 cannot be deleted because it is primary"}
{"level":"debug","ts":"2025-01-11T02:05:07.084Z","caller":"datastore/data_store.go:1002","msg":"ENI eni-098689bba2b6e8cbe cannot be deleted because it is required for MINIMUM_IP_TARGET: 14"}
```

4. I ended up creating pods with ips assigned secondary network interface and they continued to get the routable ips.

The `journalctl -u systemd-networkd` do show this, means the interface is now managed by aws-cni .

```
Jan 11 02:00:47 ip-192-168-74-236.us-west-2.compute.internal systemd-networkd[1517]: ens5: Reconfiguring with /usr/lib/systemd/network/80-ec2.network.
Jan 11 02:00:47 ip-192-168-74-236.us-west-2.compute.internal systemd-networkd[1517]: ens5: DHCP lease lost
Jan 11 02:00:47 ip-192-168-74-236.us-west-2.compute.internal systemd-networkd[1517]: ens5: DHCPv6 lease lost
Jan 11 02:00:47 ip-192-168-74-236.us-west-2.compute.internal systemd-networkd[1517]: ens5: DHCPv4 address 192.168.74.236/19, gateway 192.168.64.1 acquired from 192.168.64.1
Jan 11 02:01:16 ip-192-168-74-236.us-west-2.compute.internal systemd-networkd[1517]: eth0: Interface name change detected, renamed to ens6.
```

--- 

1. Do you only this when you setup `MINIMUM_IP_TARGET` ?
2. Assuming this race condition, perhaps I try the above steps couple of times to see I end with non routable secondary IP address? 

Do the above steps look close to how you have been reproducing this issue?

**Comment by dracut5** [comment]
Hi @orsenthil, 

Have you had any success with reproducing the issue? Maybe, you need additional details about our configuration?

**Comment by dracut5** [comment]
Is there any chance that the issue could be reproduces and fixed?
From my side, I have provided all available information about how we were able to identify the problem.
Thank you!

**Comment by orsenthil** [comment]
@dracut5 , we haven't been able to reproduce this with AL2023 so far. We don't use `terraform-aws-eks` or use a any init script with sleeps. Is it possible that those combinations are leading to the issue you are seeing. Can you see if you can reproduce this with eksctl?

**Comment by dracut5** [comment]
I can't promise that it will be fast, but I will try to use eksctl.

Regarding init scripts, it might be, therefore I have added a mention about such usage. Of course, we haven't used `sleep` command as only one singular entry, it was provided as an example to imitate some user data execution.

**Comment by ryantepera** [comment]
Hello, @dracut5 did you ever find a long term solution to this issue? I believe I am running into it when trying to upgrade to al2023 ami's from al2 on eks.

**Comment by ryantepera** [comment]
I run into almost the exact same issue fairly consistently and the only thing that resolves is restarting the CNI pod running on that particular node. I've also already added the recommended eks-ami networking configurations but pods intermittently still cannot resolve services/cluster api.

@orsenthil Could we reopen this issue?

**Comment by dracut5** [comment]
Hi @ryantepera 

I am still leveraging that workaround specifying `MINIMUM_IP_TARGET = 9`, so at the instance start there is only one ENI, a second one is added when pods are scheduled to the instance due a need of having more IPs.

That's, probably, all we can do and it works for each new node initialization, we haven't faced the issue so far.

**Comment by ryantepera** [comment]
> Hi [@ryantepera](https://github.com/ryantepera)
> 
> I am still leveraging that workaround specifying `MINIMUM_IP_TARGET = 9`, so at the instance start there is only one ENI, a second one is added when pods are scheduled to the instance due a need of having more IPs.
> 
> That's, probably, all we can do and it works for each new node initialization, we haven't faced the issue so far.

I think I understand your workaround. However, if you are using different types of instances all throughout the cluster in different nodegroups it is difficult to specify a correct `MINIMUM_IP_TARGET` in more complex environments.
